db.words.insertMany([
    {
        "name": "家",
        "internationalName": "jia",
        "language": "Cn",
        "subject": ["general"],
        "level": 0,
        "translations": [{"name": "Famille", "internationalName": "Famille", "language": "fr", "sentences": [{"sentence": "我想我的家", "translatedSentence": "Ma famille me manque"}], "rank": 0}],
        "comments": "",
        "validated": true,
        "visibility": "Visitor",
    }, {
        "name": "茶",
        "internationalName": "cha",
        "language": "Cn",
        "subject": ["general"],
        "level": 0,
        "translations": [{"name": "Thé", "internationalName": "Thé", "language": "fr", "sentences": [{"sentence": "我喜欢喝茶", "translatedSentence": "Jaime boire du thé"}], "rank": 0}],
        "comments": "",
        "validated": true,
        "visibility": "Visitor",
    }, {
        "name": "月",
        "internationalName": "yue",
        "language": "Cn",
        "subject": ["general"],
        "level": 0,
        "translations": [{"name": "Mois", "internationalName": "Mois", "language": "fr", "sentences": [{"sentence": "月", "translatedSentence": "Mois"}], "rank": 0}],
        "comments": "",
        "validated": true,
        "visibility": "Visitor",
    }, {
        "name": "太阳",
        "internationalName": "tai yang",
        "language": "Cn",
        "subject": ["general"],
        "level": 0,
        "translations": [{"name": "Soleil", "internationalName": "Soleil", "language": "fr", "sentences": [{"sentence": "太阳", "translatedSentence": "Soleil"}], "rank": 0}],
        "comments": "",
        "validated": true, 
        "visibility": "Visitor",
    }, {
        "name": "天",
        "internationalName": "tian",
        "language": "Cn",
        "subject": ["general"],
        "level": 0,
        "translations": [{"name": "Ciel", "internationalName": "Ciel", "language": "fr", "sentences": [{"sentence": "ciel", "translatedSentence": "Ciel"}], "rank": 0}],
        "comments": "",
        "validated": true,
        "visibility": "Visitor",
    }
]);